$(document).ready(function(){
        $('.slider').slick({
        arrows:true,
        dots:true,
        autoplay:true,
        autoplaySpeed:3000,
        touchTreshhold:10,
        vertical:false,
        verticalSwiping:false,
        infinite:true,
        rows:1,
    });
});